version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: meuapps-teamspeak6_server_1
      APP_PORT: 10080

  server:
    image: teamspeaksystems/teamspeak6-server:6.0.0-beta10
    restart: unless-stopped
    ports:
      - "9987:9987/udp"
      - "30033:30033/tcp"
    environment:
      - TSSERVER_LICENSE_ACCEPTED=accept
    volumes:
      - ${APP_DATA_DIR}/data:/var/tsserver
